apiVersion: v1
kind: Secret
metadata:
  name: agrocoffee-secrets
  namespace: agrocoffee
type: Opaque
stringData:
  POSTGRES_DB: "agrocoffee"
  POSTGRES_USER: "agrocoffee_user"
  POSTGRES_PASSWORD: "REEMPLAZAR_PASSWORD"
  SECRET_KEY: "REEMPLAZAR_CON_AL_MENOS_32_CARACTERES"
  DATABASE_URL: "postgresql+psycopg://agrocoffee_user:REEMPLAZAR_PASSWORD@postgres:5432/agrocoffee"
