"""crear esquema inicial

Revision ID: 17feacbef8bd
Revises: 
Create Date: 2026-09-22 21:37:04.695646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17feacbef8bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('pass', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), server_default='PRODUCTOR', nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('dispositivo',
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_dispositivo'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_dispositivo_id_usuario'), 'dispositivo', ['id_usuario'], unique=False)
    op.create_table('lote_cafe',
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=50), nullable=False),
    sa.Column('cantidad_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('humedad_inicial', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_lote'),
    sa.UniqueConstraint('codigo_lote')
    )
    op.create_index(op.f('ix_lote_cafe_id_usuario'), 'lote_cafe', ['id_usuario'], unique=False)
    op.create_table('proceso_secado',
    sa.Column('id_proceso', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='EN_PROCESO', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lote_cafe.id_lote'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_proceso')
    )
    op.create_index('ix_proceso_secado_lote_estado', 'proceso_secado', ['id_lote', 'estado'], unique=False)
    op.create_table('sensor',
    sa.Column('id_sensor', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('tipo_sensor', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad_medida', sa.String(length=30), nullable=True),
    sa.Column('pin', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo.id_dispositivo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sensor')
    )
    op.create_index(op.f('ix_sensor_id_dispositivo'), 'sensor', ['id_dispositivo'], unique=False)
    op.create_table('medicion',
    sa.Column('id_medicion', sa.Integer(), nullable=False),
    sa.Column('id_proceso', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('temperatura', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humedad_ambiental', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humedad_cafe', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('luminosidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_transcurrido_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo.id_dispositivo'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_proceso'], ['proceso_secado.id_proceso'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_medicion')
    )
    op.create_index(op.f('ix_medicion_id_dispositivo'), 'medicion', ['id_dispositivo'], unique=False)
    op.create_index('ix_medicion_proceso_fecha', 'medicion', ['id_proceso', 'fecha_hora'], unique=False)
    op.create_table('alerta',
    sa.Column('id_alerta', sa.Integer(), nullable=False),
    sa.Column('id_proceso', sa.Integer(), nullable=False),
    sa.Column('id_medicion', sa.Integer(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atendida', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fecha_atencion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_medicion'], ['medicion.id_medicion'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_proceso'], ['proceso_secado.id_proceso'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_index('ix_alerta_proceso_fecha', 'alerta', ['id_proceso', 'fecha_hora'], unique=False)
    op.create_table('prediccion',
    sa.Column('id_prediccion', sa.Integer(), nullable=False),
    sa.Column('id_medicion', sa.Integer(), nullable=False),
    sa.Column('estado_secado', sa.String(length=50), nullable=False),
    sa.Column('tiempo_restante_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nivel_confianza', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('modelo_version', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_medicion'], ['medicion.id_medicion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_prediccion')
    )
    op.create_index('ix_prediccion_medicion_fecha', 'prediccion', ['id_medicion', 'fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prediccion_medicion_fecha', table_name='prediccion')
    op.drop_table('prediccion')
    op.drop_index('ix_alerta_proceso_fecha', table_name='alerta')
    op.drop_table('alerta')
    op.drop_index('ix_medicion_proceso_fecha', table_name='medicion')
    op.drop_index(op.f('ix_medicion_id_dispositivo'), table_name='medicion')
    op.drop_table('medicion')
    op.drop_index(op.f('ix_sensor_id_dispositivo'), table_name='sensor')
    op.drop_table('sensor')
    op.drop_index('ix_proceso_secado_lote_estado', table_name='proceso_secado')
    op.drop_table('proceso_secado')
    op.drop_index(op.f('ix_lote_cafe_id_usuario'), table_name='lote_cafe')
    op.drop_table('lote_cafe')
    op.drop_index(op.f('ix_dispositivo_id_usuario'), table_name='dispositivo')
    op.drop_table('dispositivo')
    op.drop_table('usuario')
    # ### end Alembic commands ###
